### PR TITLE
Make is_enabled optional for cost_centers + fix the description of restricted_spender_user_ids

### PR DESCRIPTION
**Pull request by modernwarfareuplink**

### CODE REVIEW

**Comment by modernwarfareuplink** [comment]
New:
Screenshot 2022-05-19 at 3 45 59 PM

Old:
Screenshot 2022-05-19 at 3 48 43 PM

**Comment by viiicky** [comment]
resitricted_spender_user_ids description has project in it - it should be cc

**Comment by modernwarfareuplink** [comment]
> resitricted_spender_user_ids description has project in it - it should be cc

Have fixed this. Will check why the bundling is failing @viiicky

**Review by viiicky — APPROVED** [review]

**Comment by viiicky** [comment]
somewhere, we should also document that the `row` number is counted from 0, and not 1.
Because when we are throwing error, we are returning the row number(came to know from the other PR). The user might be looking the error in `n`th row, while, we meant `n-1`th row

**Comment by modernwarfareuplink** [comment]
> somewhere, we should also document that the `row` number is counted from 0, and not 1. Because when we are throwing error, we are returning the row number(came to know from the other PR). The user might be looking the error in `n`th row, while, we meant `n-1`th row

The bulk error format is similar to /employees/invite/bulk, where the row number starts from 0. fyi
```{
    "data": {
        "0": {
            "user_email": [
                "Missing data for required field."
            ]
        },
        "1": {
            "user_email": [
                "Missing data for required field."
            ]
        },
        "2": {
            "user_email": [
                "Missing data for required field."
            ]
        }
    },
    "error": "ValidationError",
    "message": null
}```

**Comment by modernwarfareuplink** [comment]
> > somewhere, we should also document that the `row` number is counted from 0, and not 1. Because when we are throwing error, we are returning the row number(came to know from the other PR). The user might be looking the error in `n`th row, while, we meant `n-1`th row
> 
> The bulk error format is similar to /employees/invite/bulk, where the row number starts from 0. fyi
> 
> ```
>     "data": {
>         "0": {
>             "user_email": [
>                 "Missing data for required field."
>             ]
>         },
>         "1": {
>             "user_email": [
>                 "Missing data for required field."
>             ]
>         },
>         "2": {
>             "user_email": [
>                 "Missing data for required field."
>             ]
>         }
>     },
>     "error": "ValidationError",
>     "message": null
> }```
> ```

Will add a backlog task to mention this in the doc. https://app.clickup.com/t/2dmh7ad

**Review by aditya999123 — APPROVED** [review]

**Pull request merged**
